### ISSUE TITLE
consider packaging with poetry

### ISSUE THREAD

**Issue by happysalada** [Unstructured-IO/unstructured-api#111]
Did you consider poetry for packaging ?
I would like to package this for nixos (a linux based distribution), and poetry makes building the application reproducible, which makes packaging for linux distribution much easier.
Just wondering if you have anything against it or if there are requirements that poetry wouldn't meet.

**Comment by awalker4** [comment]
Hi there, thanks for the suggestion! I'm personally not familiar with Poetry. We now have prebuilt docker images for both the [api here](https://github.com/Unstructured-IO/unstructured-api#dizzy-instructions-for-using-the-docker-image) and our [core library](https://github.com/Unstructured-IO/unstructured#dizzy-instructions-for-using-the-docker-image). This removes the complexity of having to install all our os dependencies (detectron, tesseract, etc). Does this suit your needs, or is there an aspect of this that Poetry would make easier?

**Comment by happysalada** [comment]
Thanks a lot for your quick answer!
Nixos prefers building things from source, you can supply dependencies and make sure the build has a particular sha:256
Some advantages is that you can prevent supply chain attacks for example.
Supplying binary dependencies is not a problem at all, its just that python package resolution is not deterministic, depending on when you run it, you have different package versions for dependencies. Its then impossible for anyone to reproduce what someone else has obtained. Docker builds suffer from the same problem. If someone tried to build the docker image locally they would get different layers than the image you supplied.
The one and only feature that poetry provides that is needed is the lockfile so that all the packages installed are completely determined.

Im happy to go into more details if you want.
I completely understand if this seems like too much of a niche use case .

**Comment by happysalada** [comment]
I've finished packaging this for nixos
https://github.com/NixOS/nixpkgs/pull/251318
I'm now considering adding a systemd service for it.
If you ever have recommendations regarding the systemd service, feel free to ping me. 
I'm going to close this issue as I'm not sure it's still relevant.

**Comment by awalker4** [comment]
Excellent work on the package! Perhaps our readme needs a section on other distributions - feel free to open a pr!

**Comment by happysalada** [comment]
Sounds good!
Im going to do more testing in a couple of weeks once i get access to my server again. Once im relatively confident this works well, ill add the section to the readme.
