### ISSUE TITLE
"auto" is invalid strategy for pdfs

### ISSUE THREAD

**Issue by demux79** [Unstructured-IO/unstructured-api#116]
When using the API and selecting the "auto" strategy for processing PDF files, an error occurs stating that the strategy is invalid. According to the documentation, there should be three available strategies: hi_res, fast, and auto.

Error: "Invalid strategy: auto. Must be one of ['fast', 'hi_res']"

**Comment by awalker4** [comment]
`auto` parameter is now live on api.unstructured.io.
