### ISSUE TITLE
Question: Is there a way to use the ocr_languages parameter with the API

### ISSUE THREAD

**Issue by demux79** [Unstructured-IO/unstructured-api#123]
Images and PDF support the ocr_languages parameter in unstructured. Is this supported by the API as well?

**Comment by yuming-long** [comment]
Hi @demux79, Thank you for bring this issue! I've merged a PR for this but haven't deploy the image to our API yet. For now you could use `http://localhost:8000/general/v0/general` with ocr parameters. I will let you know once i deployed it.

**Comment by yuming-long** [comment]
okay its deployed to `https://api.unstructured.io/general/v0/general` 🙏
