### ISSUE TITLE
Extract table structure with partition_via_api method

### ISSUE THREAD

**Issue by Buckler89** [Unstructured-IO/unstructured-api#138]
Hello,
  i'm using docker to run unstructured. So I need to use the  partition_via_api method to extract data from pdf. 
The extraction give me some element of table but only with plain text. I need to build pandas dataframe with the tables information. 
Maybe the option infer_table_structure could help me, but how to use this option with partition_via_api methods?
The documentation is not so clear about that.

Thanks,

**Comment by MthwRobinson** [comment]
@Buckler89 - Thanks for adding this issue. We're planning to add `infer_table_structured` to the API very soon. Once it's added, you'll be able to use it with `partition_via_api` by passing it in as a [`request_kwarg`](https://github.com/Unstructured-IO/unstructured/blob/main/unstructured/partition/api.py#L22). We'll make sure to update the docs to reflect that as well.

**Comment by yuming-long** [comment]
Hi @Buckler89, We have added `pdf_infer_table_structure` to the API as of `v0.0.30`. Here is the code snipt i used when testing `partition_via_api`:
```
from unstructured.partition.api import partition_via_api

filename="example-docs/layout-parser-paper.pdf"
elements = partition_via_api(filename=filename, strategy="hi_res", pdf_infer_table_structure=True, api_key=<your_api_key>)
print([el.metadata.text_as_html for el in elements if el.metadata.text_as_html])
```
If you are looking for documentation, you could also check the [README page](https://github.com/Unstructured-IO/unstructured-api#pdf-table-extraction) on unstructured-api repo.
