### ISSUE TITLE
service locally version CORS  domain error，help me

### ISSUE THREAD

**Issue by kill136** [Unstructured-IO/unstructured-api#144]
docker+unstructured-api locally hosts

Access to fetch at 'http://223.240.77.64:8000/general/v0/general' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
VM15891 QGOe:98     POST http://223.240.77.64:8000/general/v0/general net::ERR_FAILED

**Comment by rbiseck3** [comment]
When running your docker container, you should be able to set the `ALLOWED_ORIGINS` environment variable to a comma-delimited string of origins that get passed through the CORS check. So I believe setting that to `localhost` would prevent this problem.

**Comment by kill136** [comment]
thanks  for answer me ，i try  your idea ，but  it come out a new error below

#
![1688625841767](https://github.com/Unstructured-IO/unstructured-api/assets/22001343/f1e509aa-013b-47c6-8a9b-6e64765deb64)

Access to fetch at 'http://223.240.77.64:8000/general/v0.0.29/general' from origin 'http://localhost' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by kill136** [comment]
> When running your docker container, you should be able to set the `ALLOWED_ORIGINS` environment variable to a comma-delimited string of origins that get passed through the CORS check. So I believe setting that to `localhost` would prevent this problem.

**Comment by rbiseck3** [comment]
Are there any logs in the docker container associated with the error?

**Comment by kill136** [comment]
> Are there any logs in the docker container associated with the error?

![1688695639765](https://github.com/Unstructured-IO/unstructured-api/assets/22001343/973d5f64-fba0-4564-b715-b07cee577c45)
yes it have

**Comment by rbiseck3** [comment]
@kill136, how are you sending the original request? Is it from a browser?

**Comment by glorat** [comment]
Also worth trying to temporarily set ALLOWED_ORIGINS to * while debugging to rule out server side issues

**Comment by kill136** [comment]
> @kill136, how are you sending the original request? Is it from a browser? You can typically start your browser with things like CORS disabled. For chrome you can use the `--disable-web-security` flag. This should circumvent the CORS issue.
> 
> Also can you copy the request as a curl command and post it here?
thanks for answer.
1. OPTIONS request
curl 'http://223.240.77.64:8000/general/v0.0.29/general' \
  -X 'OPTIONS' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Access-Control-Request-Headers: access-control-allow-origin,content-type,unstructured-api-key' \
  -H 'Access-Control-Request-Method: POST' \
  -H 'Origin: http://localhost' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost/' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --compressed \
  --insecure ;
curl 'http://223.240.77.64:8000/general/v0.0.29/general' \
  -H 'Access-Control-Allow-Origin: *' \
  -H 'UNSTRUCTURED-API-KEY: 888' \
  -H 'Referer: http://localhost/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/json' \
  --data-raw $'------WebKitFormBoundaryOKCwgFXhrrKqDqnn\r\nContent-Disposition: form-data; name="files"; filename="stanley-cups.csv"\r\nContent-Type: text/csv\r\n\r\n\r\n------WebKitFormBoundaryOKCwgFXhrrKqDqnn\r\nContent-Disposition: form-data; name="strategy"\r\n\r\nhi_res\r\n------WebKitFormBoundaryOKCwgFXhrrKqDqnn--\r\n' \
  --compressed ;
curl 'http://tcb-api.tencentcloudapi.com/web?env=tcb-4k3e8z5arzs6pst-7cc5b7ad51cb' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Origin: http://localhost' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'X-SDK-Version: 1.3.5' \
  -H 'X-TCB-Trace: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZjEzOTdmOTVlYmM0NDAzNTg3M2RlNGIxODVmNTM3NGMiLCJsYXN0UmVwb3J0VGltZSI6MTY4ODk1NjgzODgzNiwiaWF0IjoxNjg4OTU2ODM4fQ.Mz3BU9EbtvYlFj4Qur4s0g-jEgCU9tvUjPtEImBVp_M' \
  -H 'content-type: application/json' \
  -H 'x-seqid: 19883166db1fe' \
  --data-raw '{"action":"storage.getUploadMetadata","env":"tcb-4k3e8z5arzs6pst-7cc5b7ad51cb","dataVersion":"2019-08-16","path":"1688958297887_0.csv","access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wibG9naW5UeXBlXCI6XCJBTk9OWU1PVVNcIixcImVudk5hbWVcIjpcInRjYi00azNlOHo1YXJ6czZwc3QtN2NjNWI3YWQ1MWNiXCIsXCJ1dWlkXCI6XCJmMTM5N2Y5NWViYzQ0MDM1ODczZGU0YjE4NWY1Mzc0Y1wifSIsImlhdCI6MTY4ODk1NjgzOCwiZXhwIjoxNjg4OTYwNDM4fQ.rz3EIulTS7ADSw4pXFWbYj2owf-R96F8jrXvzNfyg7Q;1688956838","seqId":"19883166db1fe"}' \
  --compressed \
  --insecure ;
curl 'https://cos.ap-shanghai.myqcloud.com/7463-tcb-4k3e8z5arzs6pst-7cc5b7ad51cb-1308929159/1688958297887_0.csv' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryJzmYdAqzGsDgfkwB' \
  -H 'Origin: http://localhost' \
  -H 'Referer: http://localhost/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'X-SDK-Version: 1.3.5' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'x-seqid: f2949629dc1ea' \
  --data-raw $'------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="key"\r\n\r\n1688958297887_0.csv\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="signature"\r\n\r\nq-sign-algorithm=sha1&q-ak=AKIDsuJ-Hez0lkg2Ad2BNsXG9qbgawm4hJWmPVom6Sm9LE7JWCK64I5yENnAFu279xfW&q-sign-time=1688958301;1688959201&q-key-time=1688958301;1688959201&q-header-list=&q-url-param-list=&q-signature=ebfd6b9fc757b97116dc9ca010417164c7629ae4\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="x-cos-meta-fileid"\r\n\r\nHOHmAIK0urReLUdJtPPsg1suLbN0rFmLkxvdx7+/GJaEJ/ECD3pbmqYezf5SAJvc3lRPNlTvF1i2uzab16KBPb6+7m0H1DLSH1eQCeSMcDGYKWcfeqXNYblcciUQGEhrT3vPbVQxQV9t9nWYQgGZ98sWTLD31MejtKBmtoiaAlkjzjtyuKZkrd6PQNEzwxvq/FG09F9tfbvo0SlzPHQNeBAhl+LCqceXEagB1VLD7uM=\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="success_action_status"\r\n\r\n201\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="x-cos-security-token"\r\n\r\nIYCq7p3i09cQnBGaoBg9S0KYEL1ZE32a95409c99c9b6798cfcdb145a8a622ff8dSb9YDm1tynC-xG0Ck7ZNqKwayieaEeSR_dmZ3rRUbpitc11IC_1bMustzEQYuBgVw0bQ5qn51Uwfkxe94AToFj-1quiYn1Mtf-4kOEZAcITviBmj3bzZUDwS857b5irpuFMvEQDkRu6ldVGaltTVRiUpBobVws77H7sAnNhLXX22aDohSoYb9xjrUUFiSvrhPIPvGNGNvhuAvm9YGWbTnpbkBB5fa_K9nPHNQiZEgU3dgKSibMa8hlGMehH9-s04TURI9Z_vCQCDOyphAqLzfXcQTOS2FMXcYyLxs7E4x0dAhCpEWCivbiub8k3C4pMdbzGf__gk0dPGagnQY6usXjEYUmoIrq6DnPENlNohCBFullLGxxKYSX1K9e6qYh9\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="seqId"\r\n\r\nf2949629dc1ea\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="file"; filename="stanley-cups.csv"\r\nContent-Type: text/csv\r\n\r\n\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB--\r\n' \
  --compressed ;
curl 'https://cos.ap-shanghai.myqcloud.com/7463-tcb-4k3e8z5arzs6pst-7cc5b7ad51cb-1308929159/1688958297887_0.csv' \
  -X 'OPTIONS' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Access-Control-Request-Headers: x-sdk-version,x-seqid' \
  -H 'Access-Control-Request-Method: POST' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost' \
  -H 'Referer: http://localhost/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --compressed ;
curl 'http://tcb-api.tencentcloudapi.com/web?env=tcb-4k3e8z5arzs6pst-7cc5b7ad51cb' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Origin: http://localhost' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'X-SDK-Version: 1.3.5' \
  -H 'X-TCB-Trace: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZjEzOTdmOTVlYmM0NDAzNTg3M2RlNGIxODVmNTM3NGMiLCJsYXN0UmVwb3J0VGltZSI6MTY4ODk1NjgzODgzNiwiaWF0IjoxNjg4OTU2ODM4fQ.Mz3BU9EbtvYlFj4Qur4s0g-jEgCU9tvUjPtEImBVp_M' \
  -H 'content-type: application/json' \
  -H 'x-seqid: 1d9e3fed05da2' \
  --data-raw '{"action":"storage.batchGetDownloadUrl","env":"tcb-4k3e8z5arzs6pst-7cc5b7ad51cb","dataVersion":"2019-08-16","file_list":[{"fileid":"cloud://tcb-4k3e8z5arzs6pst-7cc5b7ad51cb.7463-tcb-4k3e8z5arzs6pst-7cc5b7ad51cb-1308929159/1688958297887_0.csv"}],"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wibG9naW5UeXBlXCI6XCJBTk9OWU1PVVNcIixcImVudk5hbWVcIjpcInRjYi00azNlOHo1YXJ6czZwc3QtN2NjNWI3YWQ1MWNiXCIsXCJ1dWlkXCI6XCJmMTM5N2Y5NWViYzQ0MDM1ODczZGU0YjE4NWY1Mzc0Y1wifSIsImlhdCI6MTY4ODk1NjgzOCwiZXhwIjoxNjg4OTYwNDM4fQ.rz3EIulTS7ADSw4pXFWbYj2owf-R96F8jrXvzNfyg7Q;1688956838","seqId":"1d9e3fed05da2"}' \
  --compressed \
  --insecure ;
curl 'http://tcb-api.tencentcloudapi.com/web?env=tcb-4k3e8z5arzs6pst-7cc5b7ad51cb' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Origin: http://localhost' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'X-SDK-Version: 1.3.5' \
  -H 'X-TCB-Trace: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZjEzOTdmOTVlYmM0NDAzNTg3M2RlNGIxODVmNTM3NGMiLCJsYXN0UmVwb3J0VGltZSI6MTY4ODk1NjgzODgzNiwiaWF0IjoxNjg4OTU2ODM4fQ.Mz3BU9EbtvYlFj4Qur4s0g-jEgCU9tvUjPtEImBVp_M' \
  -H 'content-type: application/json' \
  -H 'x-seqid: ca072a4a1be81' \
  --data-raw '{"action":"storage.batchGetDownloadUrl","env":"tcb-4k3e8z5arzs6pst-7cc5b7ad51cb","dataVersion":"2019-08-16","file_list":[{"fileid":"cloud://tcb-4k3e8z5arzs6pst-7cc5b7ad51cb.7463-tcb-4k3e8z5arzs6pst-7cc5b7ad51cb-1308929159/1688958297887_0.csv"}],"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wibG9naW5UeXBlXCI6XCJBTk9OWU1PVVNcIixcImVudk5hbWVcIjpcInRjYi00azNlOHo1YXJ6czZwc3QtN2NjNWI3YWQ1MWNiXCIsXCJ1dWlkXCI6XCJmMTM5N2Y5NWViYzQ0MDM1ODczZGU0YjE4NWY1Mzc0Y1wifSIsImlhdCI6MTY4ODk1NjgzOCwiZXhwIjoxNjg4OTYwNDM4fQ.rz3EIulTS7ADSw4pXFWbYj2owf-R96F8jrXvzNfyg7Q;1688956838","seqId":"ca072a4a1be81"}' \
  --compressed \
  --insecure

2.real request
curl 'http://223.240.77.64:8000/general/v0.0.29/general' \
  -X 'OPTIONS' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Access-Control-Request-Headers: access-control-allow-origin,content-type,unstructured-api-key' \
  -H 'Access-Control-Request-Method: POST' \
  -H 'Origin: http://localhost' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost/' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --compressed \
  --insecure ;
curl 'http://223.240.77.64:8000/general/v0.0.29/general' \
  -H 'Access-Control-Allow-Origin: *' \
  -H 'UNSTRUCTURED-API-KEY: 888' \
  -H 'Referer: http://localhost/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/json' \
  --data-raw $'------WebKitFormBoundaryOKCwgFXhrrKqDqnn\r\nContent-Disposition: form-data; name="files"; filename="stanley-cups.csv"\r\nContent-Type: text/csv\r\n\r\n\r\n------WebKitFormBoundaryOKCwgFXhrrKqDqnn\r\nContent-Disposition: form-data; name="strategy"\r\n\r\nhi_res\r\n------WebKitFormBoundaryOKCwgFXhrrKqDqnn--\r\n' \
  --compressed ;
curl 'http://tcb-api.tencentcloudapi.com/web?env=tcb-4k3e8z5arzs6pst-7cc5b7ad51cb' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Origin: http://localhost' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'X-SDK-Version: 1.3.5' \
  -H 'X-TCB-Trace: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZjEzOTdmOTVlYmM0NDAzNTg3M2RlNGIxODVmNTM3NGMiLCJsYXN0UmVwb3J0VGltZSI6MTY4ODk1NjgzODgzNiwiaWF0IjoxNjg4OTU2ODM4fQ.Mz3BU9EbtvYlFj4Qur4s0g-jEgCU9tvUjPtEImBVp_M' \
  -H 'content-type: application/json' \
  -H 'x-seqid: 19883166db1fe' \
  --data-raw '{"action":"storage.getUploadMetadata","env":"tcb-4k3e8z5arzs6pst-7cc5b7ad51cb","dataVersion":"2019-08-16","path":"1688958297887_0.csv","access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wibG9naW5UeXBlXCI6XCJBTk9OWU1PVVNcIixcImVudk5hbWVcIjpcInRjYi00azNlOHo1YXJ6czZwc3QtN2NjNWI3YWQ1MWNiXCIsXCJ1dWlkXCI6XCJmMTM5N2Y5NWViYzQ0MDM1ODczZGU0YjE4NWY1Mzc0Y1wifSIsImlhdCI6MTY4ODk1NjgzOCwiZXhwIjoxNjg4OTYwNDM4fQ.rz3EIulTS7ADSw4pXFWbYj2owf-R96F8jrXvzNfyg7Q;1688956838","seqId":"19883166db1fe"}' \
  --compressed \
  --insecure ;
curl 'https://cos.ap-shanghai.myqcloud.com/7463-tcb-4k3e8z5arzs6pst-7cc5b7ad51cb-1308929159/1688958297887_0.csv' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryJzmYdAqzGsDgfkwB' \
  -H 'Origin: http://localhost' \
  -H 'Referer: http://localhost/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'X-SDK-Version: 1.3.5' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'x-seqid: f2949629dc1ea' \
  --data-raw $'------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="key"\r\n\r\n1688958297887_0.csv\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="signature"\r\n\r\nq-sign-algorithm=sha1&q-ak=AKIDsuJ-Hez0lkg2Ad2BNsXG9qbgawm4hJWmPVom6Sm9LE7JWCK64I5yENnAFu279xfW&q-sign-time=1688958301;1688959201&q-key-time=1688958301;1688959201&q-header-list=&q-url-param-list=&q-signature=ebfd6b9fc757b97116dc9ca010417164c7629ae4\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="x-cos-meta-fileid"\r\n\r\nHOHmAIK0urReLUdJtPPsg1suLbN0rFmLkxvdx7+/GJaEJ/ECD3pbmqYezf5SAJvc3lRPNlTvF1i2uzab16KBPb6+7m0H1DLSH1eQCeSMcDGYKWcfeqXNYblcciUQGEhrT3vPbVQxQV9t9nWYQgGZ98sWTLD31MejtKBmtoiaAlkjzjtyuKZkrd6PQNEzwxvq/FG09F9tfbvo0SlzPHQNeBAhl+LCqceXEagB1VLD7uM=\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="success_action_status"\r\n\r\n201\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="x-cos-security-token"\r\n\r\nIYCq7p3i09cQnBGaoBg9S0KYEL1ZE32a95409c99c9b6798cfcdb145a8a622ff8dSb9YDm1tynC-xG0Ck7ZNqKwayieaEeSR_dmZ3rRUbpitc11IC_1bMustzEQYuBgVw0bQ5qn51Uwfkxe94AToFj-1quiYn1Mtf-4kOEZAcITviBmj3bzZUDwS857b5irpuFMvEQDkRu6ldVGaltTVRiUpBobVws77H7sAnNhLXX22aDohSoYb9xjrUUFiSvrhPIPvGNGNvhuAvm9YGWbTnpbkBB5fa_K9nPHNQiZEgU3dgKSibMa8hlGMehH9-s04TURI9Z_vCQCDOyphAqLzfXcQTOS2FMXcYyLxs7E4x0dAhCpEWCivbiub8k3C4pMdbzGf__gk0dPGagnQY6usXjEYUmoIrq6DnPENlNohCBFullLGxxKYSX1K9e6qYh9\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="seqId"\r\n\r\nf2949629dc1ea\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB\r\nContent-Disposition: form-data; name="file"; filename="stanley-cups.csv"\r\nContent-Type: text/csv\r\n\r\n\r\n------WebKitFormBoundaryJzmYdAqzGsDgfkwB--\r\n' \
  --compressed ;
curl 'https://cos.ap-shanghai.myqcloud.com/7463-tcb-4k3e8z5arzs6pst-7cc5b7ad51cb-1308929159/1688958297887_0.csv' \
  -X 'OPTIONS' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Access-Control-Request-Headers: x-sdk-version,x-seqid' \
  -H 'Access-Control-Request-Method: POST' \
  -H 'Connection: keep-alive' \
  -H 'Origin: http://localhost' \
  -H 'Referer: http://localhost/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --compressed ;
curl 'http://tcb-api.tencentcloudapi.com/web?env=tcb-4k3e8z5arzs6pst-7cc5b7ad51cb' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Origin: http://localhost' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'X-SDK-Version: 1.3.5' \
  -H 'X-TCB-Trace: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZjEzOTdmOTVlYmM0NDAzNTg3M2RlNGIxODVmNTM3NGMiLCJsYXN0UmVwb3J0VGltZSI6MTY4ODk1NjgzODgzNiwiaWF0IjoxNjg4OTU2ODM4fQ.Mz3BU9EbtvYlFj4Qur4s0g-jEgCU9tvUjPtEImBVp_M' \
  -H 'content-type: application/json' \
  -H 'x-seqid: 1d9e3fed05da2' \
  --data-raw '{"action":"storage.batchGetDownloadUrl","env":"tcb-4k3e8z5arzs6pst-7cc5b7ad51cb","dataVersion":"2019-08-16","file_list":[{"fileid":"cloud://tcb-4k3e8z5arzs6pst-7cc5b7ad51cb.7463-tcb-4k3e8z5arzs6pst-7cc5b7ad51cb-1308929159/1688958297887_0.csv"}],"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wibG9naW5UeXBlXCI6XCJBTk9OWU1PVVNcIixcImVudk5hbWVcIjpcInRjYi00azNlOHo1YXJ6czZwc3QtN2NjNWI3YWQ1MWNiXCIsXCJ1dWlkXCI6XCJmMTM5N2Y5NWViYzQ0MDM1ODczZGU0YjE4NWY1Mzc0Y1wifSIsImlhdCI6MTY4ODk1NjgzOCwiZXhwIjoxNjg4OTYwNDM4fQ.rz3EIulTS7ADSw4pXFWbYj2owf-R96F8jrXvzNfyg7Q;1688956838","seqId":"1d9e3fed05da2"}' \
  --compressed \
  --insecure ;
curl 'http://tcb-api.tencentcloudapi.com/web?env=tcb-4k3e8z5arzs6pst-7cc5b7ad51cb' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Origin: http://localhost' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  -H 'X-SDK-Version: 1.3.5' \
  -H 'X-TCB-Trace: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZjEzOTdmOTVlYmM0NDAzNTg3M2RlNGIxODVmNTM3NGMiLCJsYXN0UmVwb3J0VGltZSI6MTY4ODk1NjgzODgzNiwiaWF0IjoxNjg4OTU2ODM4fQ.Mz3BU9EbtvYlFj4Qur4s0g-jEgCU9tvUjPtEImBVp_M' \
  -H 'content-type: application/json' \
  -H 'x-seqid: ca072a4a1be81' \
  --data-raw '{"action":"storage.batchGetDownloadUrl","env":"tcb-4k3e8z5arzs6pst-7cc5b7ad51cb","dataVersion":"2019-08-16","file_list":[{"fileid":"cloud://tcb-4k3e8z5arzs6pst-7cc5b7ad51cb.7463-tcb-4k3e8z5arzs6pst-7cc5b7ad51cb-1308929159/1688958297887_0.csv"}],"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wibG9naW5UeXBlXCI6XCJBTk9OWU1PVVNcIixcImVudk5hbWVcIjpcInRjYi00azNlOHo1YXJ6czZwc3QtN2NjNWI3YWQ1MWNiXCIsXCJ1dWlkXCI6XCJmMTM5N2Y5NWViYzQ0MDM1ODczZGU0YjE4NWY1Mzc0Y1wifSIsImlhdCI6MTY4ODk1NjgzOCwiZXhwIjoxNjg4OTYwNDM4fQ.rz3EIulTS7ADSw4pXFWbYj2owf-R96F8jrXvzNfyg7Q;1688956838","seqId":"ca072a4a1be81"}' \
  --compressed \
  --insecure ;
curl 'http://192.168.31.148/sockjs-node/info?t=1688958364309' \
  -H 'Accept: */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Origin: http://localhost' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --compressed

**Comment by kill136** [comment]
> Also worth trying to temporarily set ALLOWED_ORIGINS to * while debugging to rule out server side issues

yes,i try your option ,but come up a new problem  ,it can not analyze  pdf files

  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/home/notebook-user/nltk_data'
    - '/usr/local/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
