### ISSUE TITLE
invalid ELF header 

### ISSUE THREAD

**Issue by stefanos87** [Unstructured-IO/unstructured-api#157]
I'm using the dockerized version, unfortunately the container fails after a few seconds, here are the logs:
docker-unstructured-unstructured-api-1 | Traceback (most recent call last):
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/torch/__init__.py", line 168, in _load_global_deps
docker-unstructured-unstructured-api-1 |     ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
docker-unstructured-unstructured-api-1 |   File "/usr/local/lib/python3.8/ctypes/__init__.py", line 373, in __init__
docker-unstructured-unstructured-api-1 |     self._handle = _dlopen(self._name, mode)
docker-unstructured-unstructured-api-1 | OSError: /home/notebook-user/.local/lib/python3.8/site-packages/torch/lib/../../nvidia/curand/lib/libcurand.so.10: invalid ELF header
docker-unstructured-unstructured-api-1 | 
docker-unstructured-unstructured-api-1 | During handling of the above exception, another exception occurred:
docker-unstructured-unstructured-api-1 | 
docker-unstructured-unstructured-api-1 | Traceback (most recent call last):
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/bin/uvicorn", line 8, in <module>
docker-unstructured-unstructured-api-1 |     sys.exit(main())
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
docker-unstructured-unstructured-api-1 |     return self.main(*args, **kwargs)
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
docker-unstructured-unstructured-api-1 |     rv = self.invoke(ctx)
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
docker-unstructured-unstructured-api-1 |     return ctx.invoke(self.callback, **ctx.params)
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
docker-unstructured-unstructured-api-1 |     return __callback(*args, **kwargs)
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/uvicorn/main.py", line 410, in main
docker-unstructured-unstructured-api-1 |     run(
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/uvicorn/main.py", line 578, in run
docker-unstructured-unstructured-api-1 |     server.run()
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/uvicorn/server.py", line 61, in run
docker-unstructured-unstructured-api-1 |     return asyncio.run(self.serve(sockets=sockets))
docker-unstructured-unstructured-api-1 |   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
docker-unstructured-unstructured-api-1 |     return loop.run_until_complete(main)
docker-unstructured-unstructured-api-1 |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/uvicorn/server.py", line 68, in serve
docker-unstructured-unstructured-api-1 |     config.load()
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/uvicorn/config.py", line 473, in load
docker-unstructured-unstructured-api-1 |     self.loaded_app = import_from_string(self.app)
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/uvicorn/importer.py", line 21, in import_from_string
docker-unstructured-unstructured-api-1 |     module = importlib.import_module(module_str)
docker-unstructured-unstructured-api-1 |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
docker-unstructured-unstructured-api-1 |     return _bootstrap._gcd_import(name[level:], package, level)
docker-unstructured-unstructured-api-1 |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
docker-unstructured-unstructured-api-1 |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
docker-unstructured-unstructured-api-1 |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
docker-unstructured-unstructured-api-1 |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
docker-unstructured-unstructured-api-1 |   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
docker-unstructured-unstructured-api-1 |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/prepline_general/api/app.py", line 11, in <module>
docker-unstructured-unstructured-api-1 |     from .general import router as general_router
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/prepline_general/api/general.py", line 29, in <module>
docker-unstructured-unstructured-api-1 |     from unstructured_inference.models.chipper import MODEL_TYPES as CHIPPER_MODEL_TYPES
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/unstructured_inference/models/chipper.py", line 5, in <module>
docker-unstructured-unstructured-api-1 |     import torch
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/torch/__init__.py", line 228, in <module>
docker-unstructured-unstructured-api-1 |     _load_global_deps()
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/torch/__init__.py", line 189, in _load_global_deps
docker-unstructured-unstructured-api-1 |     _preload_cuda_deps(lib_folder, lib_name)
docker-unstructured-unstructured-api-1 |   File "/home/notebook-user/.local/lib/python3.8/site-packages/torch/__init__.py", line 155, in _preload_cuda_deps
docker-unstructured-unstructured-api-1 |     ctypes.CDLL(lib_path)
docker-unstructured-unstructured-api-1 |   File "/usr/local/lib/python3.8/ctypes/__init__.py", line 373, in __init__
docker-unstructured-unstructured-api-1 |     self._handle = _dlopen(self._name, mode)
docker-unstructured-unstructured-api-1 | OSError: /home/notebook-user/.local/lib/python3.8/site-packages/nvidia/curand/lib/libcurand.so.10: invalid ELF header

**Comment by awalker4** [comment]
Hi there, sorry for the late response. Are you still seeing this issue with the latest `unstructured-api`?

**Comment by awalker4** [comment]
Will close this for now - let us know if this is still an issue.
