### ISSUE TITLE
unblocking requests from localhost

### ISSUE THREAD

**Issue by happysalada** [Unstructured-IO/unstructured-api#164]
hey, first of all, I want to express my gratitude for this project!
I think it's amazing and I'm almost done packaging it for nixos. (if you are interested in the developments, please let me know your handle and I would be happy to tag you in the PRs. So far I've just packaged unstructured, so I'm missing packaging unstructured-api and paddle-OCR. All the rest is done, it's *almost* there).

While testing the generously made public available server, it seems that you are blocking requests made from localhost. I've got a small server that I like to test locally with. I noticed that the requests work when the server is deployed but they don't work on my local environment.

I'm wondering if there is any way to disable that, no worries if there isn't.

**Comment by awalker4** [comment]
Hmm, I can't think of anything that _should_ cause an error talking from localhost. What response are you seeing?

**Comment by happysalada** [comment]
No responses at all. The request errors in a timeout.
I dont think its a big deal, since anyways this works when deployed to production. Maybe we just leave this issue open for other people encountering the error.
Of course if you want me to test anything, im happy to.
