### ISSUE TITLE
"fast" output returned for "hi_res"

### ISSUE THREAD

**Issue by cragwolfe** [Unstructured-IO/unstructured-api#188]
Per this gist: https://gist.github.com/cragwolfe/7789a3653c1dad2178c65014f0132233
the `unstructured` library is returning "auto" results for "fast" and something different for "hi_res" (which is good).

However, requesting "hi_res" from the API is currently also returning fast results, as documented in
https://github.com/Unstructured-IO/unstructured/pull/1150 .

**Comment by Coniferish** [comment]
Addressed in the unstructured repo here: https://github.com/Unstructured-IO/unstructured/pull/1840
