### ISSUE TITLE
{'detail': 'API key is invalid, please provide a valid API key in the header.'}

### ISSUE THREAD

**Issue by yuanjie-ai** [Unstructured-IO/unstructured-api#204]
{'detail': 'API key is invalid, please provide a valid API key in the header.'}
![image](https://github.com/Unstructured-IO/unstructured-api/assets/20265321/44e48762-0660-456d-8c4e-bd93e464cc86)

**Comment by yuanjie-ai** [comment]
# Define the URL
url = 'https://api.unstructured.io/general/v0/general'

# Define the headers
headers = {
    'accept': 'application/json',
    'unstructured-api-key': 'YaSB70KS6XKicp1IOrgxVRL4clsHziYaSB70KS6XKicp1IOrgxVRL4clsHzi',
}

# Define the form data
data = {
    'strategy': 'auto',
}

# Define the file data
file_path = "/Users/betterme/PycharmProjects/AI/MeUtils/meutils/ai_cv/invoice.jpg"
file_data = {'files': open(file_path, 'rb')}

# Make the POST request
response = requests.post(url, headers=headers, data=data, files=file_data)

# Close the file
file_data['files'].close()

# Parse the JSON response
json_response = response.json()

**Comment by yuanjie-ai** [comment]
```
# Define the URL
url = 'https://api.unstructured.io/general/v0/general'

# Define the headers
headers = {
    'accept': 'application/json',
    'unstructured-api-key': 'YaSB70KS6XKicp1IOrgxVRL4clsHziYaSB70KS6XKicp1IOrgxVRL4clsHzi',
}

# Define the form data
data = {
    'strategy': 'auto',
}

# Define the file data
file_path = "/Users/betterme/PycharmProjects/AI/MeUtils/meutils/ai_cv/invoice.jpg"
file_data = {'files': open(file_path, 'rb')}

# Make the POST request
response = requests.post(url, headers=headers, data=data, files=file_data)

# Close the file
file_data['files'].close()

# Parse the JSON response
json_response = response.json()
```

**Comment by yuming-long** [comment]
Hi @yuanjie-ai , I just checked your provided API key is not in our database, would you mind requesting API key again and see if you receive the same API key?

**Comment by yuanjie-ai** [comment]
发自我的iPhone


------------------ Original ------------------
From: Yuming Long ***@***.***&gt;
Date: Fri,Aug 25,2023 10:37 PM
To: Unstructured-IO/unstructured-api ***@***.***&gt;
Cc: Betterme ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Unstructured-IO/unstructured-api] {'detail': 'API key isinvalid, please provide a valid API key in the header.'} (Issue #204)





 
Hi @yuanjie-ai , I just checked your provided API key is not in our database, would you mind requesting API key again and see if you receive the same API key?

**Comment by yuming-long** [comment]
close this for now, please reach out if you still have trouble with api key :)

**Comment by reachusama** [comment]
I am facing the same error. 

I created a trial account with unstructured.io, and using the FileIO API Loader with Google Drive.  I created creating a new API but gives the same error. I also tried setting up an env variable but still does not work.

**Comment by justinsyu** [comment]
Hello, I am running into this same issue as well (it just started yesterday). I tried creating a new API key and still run into the same errors. Below is my code. Please help! Thank you!

import os
from getpass import getpass

os.environ["UNSTRUCTURED_API_KEY"] = getpass("Enter your Unstructured API Key:")
os.environ["UNSTRUCTURED_API_URL"] = getpass("Enter your Unstructured API URL:")
os.environ["ASTRA_DB_API_ENDPOINT"] = input("Enter your Astra DB API Endpoint: ")
os.environ["ASTRA_DB_APPLICATION_TOKEN"] = getpass("Enter your Astra DB Token: ")
os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API Key: ")

from langchain_community.document_loaders import UnstructuredAPIFileLoader

loader = UnstructuredAPIFileLoader(
    api_key=os.environ["UNSTRUCTURED_API_KEY"],
    file_path="filename.pdf",

)
simple_docs = loader.load()
len(simple_docs)

**Comment by Coniferish** [comment]
Hi @reachusama and @justinsyu,
The 401 error is likely because you are connecting to the free api address (`https://api.unstructured.io/`) and not `https://api.unstructuredapp.io`. We are in the midst of transitioning to a single endpoint at our new [serverless API](https://docs.unstructured.io/api-reference/api-services/saas-api-development-guide). You can see both the Serverless and Free APIs listed at the top of this [landing page ](https://docs.unstructured.io/api-reference/api-services/overview), but the Free API address is being phased out. There is still a free 14-day trial for the Unstructured Serverless API (`https://api.unstructuredapp.io`), though, and that's the address you should use moving forward.

Please reach out if you still have any trouble
