### ISSUE TITLE
Can the language type of a PDF be automatically detected?

### ISSUE THREAD

**Issue by chostyouwang** [Unstructured-IO/unstructured-api#212]
If I don't specify the ocr_languages, it will default to "eng", but if the text is in a non-English language, it may result in garbled output. Is there a way to provide automatic language detection?

**Comment by cragwolfe** [comment]
DId you try passing the `ocr_languages` form parameter as described here:
https://github.com/Unstructured-IO/unstructured-api#ocr-languages ?

The languages are tesseract language codes, so for Simplified Chinese, you would want:

    -F 'ocr_languages=chi_sim'

in a curl request, for instance.

**Comment by chostyouwang** [comment]
> DId you try passing the `ocr_languages` form parameter as described here: https://github.com/Unstructured-IO/unstructured-api#ocr-languages ?
> 
> The languages are tesseract language codes, so for Simplified Chinese, you would want:
> 
> ```
> -F 'ocr_languages=chi_sim'
> ```
> 
> in a curl request, for instance.Yes, when I select "ocr_languages" as "chi_sim", it can be parsed correctly. However, the default selection is "eng", and there are dozens of optional "ocr_languages". If a non-English language appears, it will be parsed as garbled text.



> DId you try passing the `ocr_languages` form parameter as described here: https://github.com/Unstructured-IO/unstructured-api#ocr-languages ?
> 
> The languages are tesseract language codes, so for Simplified Chinese, you would want:
> 
> ```
> -F 'ocr_languages=chi_sim'
> ```
> 
> in a curl request, for instance.

Yes, when I select "ocr_languages" as "chi_sim", it can be parsed correctly. However, the default selection is "eng", and there are dozens of optional "ocr_languages". If a non-English language appears, it will be parsed as garbled text.

**Comment by cragwolfe** [comment]
> Can the language type of a PDF be automatically detected?

we are planning to support document auto-detection soon, at least for documents that contain some non-image text (most PDF's fall into this category).
