### ISSUE TITLE
doc can not extract text form image

### ISSUE THREAD

**Issue by chostyouwang** [Unstructured-IO/unstructured-api#219]
Can't OCR extract text from images stored in a .doc file, while it can do so from a PDF file? Why is that?what should i set the args

**Comment by awalker4** [comment]
Hi there - pdf files can extract text from images because the entire document is sent through OCR. Other filetypes are processed differently, and we currently don't process embedded images. Please follow this issue for updates: https://github.com/Unstructured-IO/unstructured/issues/1019
