### ISSUE TITLE
API resonse 500 error

### ISSUE THREAD

**Issue by chostyouwang** [Unstructured-IO/unstructured-api#220]
respnse 500 inner error，there is no detail information ，i can not figout it

**Comment by awalker4** [comment]
Hi there, are you able to share the file that caused this?

**Comment by chostyouwang** [comment]
When I use the API method to call the unstructured-api to parse large pdf files exceeding 100 pages, the response frequently returns a 500 error. Is this due to the size of the file? Subsequently, when I split the large PDF file into 30-page files, it can return normally.

**Comment by chostyouwang** [comment]
My PDF file has 148 pages and a size of 17.6MB. When I directly call the API for parsing, the system returns an Internal system error with code 500. However, when I split the file into the following page numbers and sizes, I can successfully parse them:

Part1: 30 pages, 21.8MB
Part2: 50 pages, 50.2MB
Part3: 68 pages, 69.4MB

I suspect that there is a page limit set by the API, but when I tried splitting the file into 100 pages and 101 pages, both were successfully parsed. However, when I split it into 138 pages, the parsing failed.

Are there any parameters in the API for parsing PDF files that limit the file size or the number of pages to be parsed? If so, what are these parameters? If the issue is related to the number of pages, I believe I need to split the file when it exceeds a certain number of pages. Are there any recommended APIs that can directly handle file splitting?

**Comment by awalker4** [comment]
Hmm, this is certainly an odd one. The api doesn't have any page limits, so I'm wondering if perhaps something is timing out. We recently updated the hosted api to improve the error messages that are returned. Can you try to reproduce the error and let us know what the response says?

**Comment by awalker4** [comment]
Hi @chostyouwang, just want to follow up on this. We're trying to prioritize spurious 500 errors. Do you have any files you can share that are getting this error?

**Comment by Jimchoo91** [comment]
Just to add, I get 502 and 504 errors. It seems connected. I am using UnstructuredAPIFileLoader from LangChain. Here are the files:

[chevron.pdf](https://github.com/Unstructured-IO/unstructured-api/files/12837448/chevron.pdf)

**Comment by MthwRobinson** [comment]
See #255. Please reopen if this recurs.
