### ISSUE TITLE
Receive unexpected status code 400 from the API.

### ISSUE THREAD

**Issue by Jimchoo91** [Unstructured-IO/unstructured-api#236]
I am running this in Python and my first PDF worked fine with the API. The first PDF was 38 pages.

I am trying now with a PDF which is 98 pages and I receive the error: "Receive unexpected status code 400 from the API.".

Any idea why?

**Comment by awalker4** [comment]
Are you able to share the pdf that caused this?

**Comment by Jimchoo91** [comment]
[shell-sustainability-report-2022.pdf](https://github.com/Unstructured-IO/unstructured-api/files/12706323/shell-sustainability-report-2022.pdf)
It was the attached, thanks.

**Comment by awalker4** [comment]
Thanks for the file - I'm able to reproduce the 400. The message from the API is that the file is encrypted. That's coming from [this check](https://github.com/Unstructured-IO/unstructured-api/blob/49fe71026e026530276bbb72f6a9df46feb6d1c2/prepline_general/api/general.py#L280), which needs to be tweaked. The file does have a password, but it's still readable.

**Comment by awalker4** [comment]
Fix has been deployed!
