### ISSUE TITLE
OCR type in api docker version

### ISSUE THREAD

**Issue by mrahmadt** [Unstructured-IO/unstructured-api#250]
Hello Team,

What type of OCR is implemented in the docker version?

I did a test for an image between the docker version and the hosted API and the result is very different, the docker version does not extract a valid text most of the time

**Comment by awalker4** [comment]
The hosted api uses the docker image as of each [release commit](https://github.com/Unstructured-IO/unstructured-api/releases), so hopefully everything should be consistent. Do you have an example file that we could test with?

**Comment by J2DOG** [comment]
I encountered the same problem, the docker version does not extract a valid text most of the time. they extract some words instead of meaningful paragraphs and sentences.
