### ISSUE TITLE
Return just text (not json)

### ISSUE THREAD

**Issue by mrahmadt** [Unstructured-IO/unstructured-api#251]
Hi

I checked github and the documentation for a way to return the full text from any document (I don't need partitioning), and I couldn't find anyone mentioned a solution

I can loop through the json output and get the "text" attribute in my code but I thought to ask you if this is already available as an option in unstructured-api

**Comment by awalker4** [comment]
Hi there, at the moment we don't have an option like this, so the solution you mentioned is probably your best bet.
