### ISSUE TITLE
Docker entry point error

### ISSUE THREAD

**Issue by glorat** [Unstructured-IO/unstructured-api#261]
https://github.com/Unstructured-IO/unstructured-api/blob/c31465029047fcfc67e401e5b8b75fae95493400/scripts/app-start.sh#L1C17-L1C17

In certain docker environments (e.g. google cloud run) this will fail with
```
env: 'bash ': No such file or directory
env: use -[v]S to pass options in shebang lines
Container called exit(127).
```
Note the space after bash

**Comment by alex-atkins** [comment]
I'm getting the same issue in 0.0.80 when running app-start.sh, but I don't see a white space.  Anyone know if there's another cause?

```
env: can't execute 'bash
': No such file or directory
```
