### ISSUE TITLE
chore: remove the versioned endpoint from the docs

### ISSUE THREAD

**Issue by awalker4** [Unstructured-IO/unstructured-api#270]
We should drop the `/general/v0.0.x/general` path and stick with `/general/v0/general`. If anyone uses the former, they'll get a 404 as soon as we release a new version.

**Comment by cragwolfe** [comment]
we should only advertise `/general/v0/general` in docs. i think having the full semver version one is also useful.

**Comment by MthwRobinson** [comment]
This is no longer in the docs
