### ISSUE TITLE
Issue parsing a certain pdf file

### ISSUE THREAD

**Issue by jashdalvi** [Unstructured-IO/unstructured-api#279]
I am getting this error while parsing a certain pdf file:
"unsupported operand type(s) for -: 'float' and 'NoneType'"

Here is the pdf file for reference
[doc_ZUcPhd7XkxOsfB.pdf](https://github.com/Unstructured-IO/unstructured-api/files/12874491/doc_ZUcPhd7XkxOsfB.pdf)

I tried with the unstructured api but the same issue persists.

**Comment by awalker4** [comment]
Hi there, thanks for the reproducer! We're tracking [over here](https://github.com/Unstructured-IO/unstructured/issues/1651), and I believe it's fixed in the latest release, we just need to verify.

**Comment by awalker4** [comment]
Will close this and link in the other issue.

**Comment by awalker4** [comment]
Confirmed that this works in unstructured 0.10.20 and the latest api release 0.0.52. This will be in the hosted api within the hour.
