### ISSUE TITLE
FR/add partition option to return pdf images and pass it through the api

### ISSUE THREAD

**Issue by ron-unstructured** [Unstructured-IO/unstructured-api#306]
**Description**
This parameter is available in the `partition_pdf` but not through the API. With the new GPT-4V multimodal model, extracting images from source documents will be helpful. 

**To Reproduce**
> from unstructured.partition.pdf import partition_pdf
> partition_pdf(filename, strategy="hi_res", extract_images_in_pdf=True)

**Comment by awalker4** [comment]
It’s important that the api can return images to match the library. The best approach is likely b64 encoded files returned in a metadata field. So, we'll need to:
* Pass the param to unstructured
* Collect the images that are saved to disk
* Add the data as a b64 string in the response

**Comment by cragwolfe** [comment]
Note that additional elements beyond `Image` such as `Table` per https://github.com/Unstructured-IO/unstructured/pull/2229  may now be extracted as images, so this should include that functionality as well.

**Comment by faileon** [comment]
Multimodal RAG is becoming hot topic so I wuld love to see this implemented officially.

So far my workaround is to spin up custom FastAPI that returns Image element and adds the base64 represenation to them. I can submit a PR to this repo if it's welcomed.

**Comment by awalker4** [comment]
A PR would always be welcome! Our current plan for this is to add an option to `partition` to return the images directly. This should mean the lift on the api side is just passing the parameter along. If this is what your workaround is doing, happy to review in the `unstructured` repo.

**Comment by mkr9395** [comment]
keeping `extract_images_in_pdf=True` solved the issue for me!
