### ISSUE TITLE
Not able to deploy on Google Cloud RUn

### ISSUE THREAD

**Issue by rebecca1001** [Unstructured-IO/unstructured-api#354]
I want to host my own version of unstructured on goole cloud run but not able to do so. I pulled the container and uploaded to google cloud build. Then I tried using it on google cloud run to start the service but it always said that server failed to listen to the port. I made sure that the port is 8000 but still does not work.

**Comment by awalker4** [comment]
Hi there! Do you have access to the container logs? The first thing I would check for is the message below, implying the server is fully up and accepting traffic.
`2024-01-26 17:23:09,945 unstructured_api INFO Started Unstructured API`

**Comment by reachusama** [comment]
This is the error that I am getting in the logs:

(terminated: Application failed to start: failed to load /home/notebook-user/scripts/app-start.sh: exec format error)

**Comment by awalker4** [comment]
Ah, this error is consistent with the docker image being built for the wrong platform. 

```
docker pull --platform=linux/arm64 quay.io/unstructured-io/unstructured-api:latest
```

**Comment by reachusama** [comment]
Ah ok. Thanks ! This is a big help!

**Comment by reachusama** [comment]
It still doesn't work. I get this error:
terminated: Application failed to start: failed to load /home/notebook-user/scripts/app-start.sh: exec format error

**Comment by kenzik** [comment]
The image doesn't listen on the PORT environment variable, which Cloud Run uses. 

You have two choices:  

 - when deploying, explitly set the port to 8000 (Unstructured image's default); or 
 - set the `UVICORN_PORT` environment on the revision to port 8080 (Cloud Run's default.)
 
Example of the latter:

![SCR-20240202-iwkz](https://github.com/Unstructured-IO/unstructured-api/assets/423503/f5bc03e9-8d05-44e8-ab8c-38628aea3dba)

**Comment by awalker4** [comment]
@reachusama Apologies - what about `docker pull --platform=linux/amd64 quay.io/unstructured-io/unstructured-api:latest`

**Comment by MthwRobinson** [comment]
Try @awalker4 's suggestion if you hit this error. I this problem recurs using the command above, we can reopen.
