### ISSUE TITLE
GPU version 

### ISSUE THREAD

**Issue by homeant** [Unstructured-IO/unstructured-api#360]
Can you provide a GPU version of the image? Local packaging is too painful.

**Comment by netapy** [comment]
+1 please :)

**Comment by kaleyroy** [comment]
+1  really need it performance acceleration under hi_res mode on PDF or IMAGE

**Comment by vespero89** [comment]
+1 please 👍

**Comment by Bryson14** [comment]
Is that why I get the error in the docker logs about "lib/python3.10/site-packages/torch/cuda/__init__.py:619: UserWarning: Can't initialize NVML"?

**Comment by MthwRobinson** [comment]
We don't plan to support a GPU version of the open source image at this time.
