### ISSUE TITLE
chunking with "overlap" in the api.

### ISSUE THREAD

**Issue by BramVR** [Unstructured-IO/unstructured-api#371]
**Describe the bug**
It is not possible to have chunking done with "overlap" from the hosted API. Although the functionality is there when using chunk_by_title sepeartely.

**To Reproduce**
from unstructured.partition.api import partition_via_api
elements = partition_via_api(file_path,
                                 api_key=unstructured_api,
                                 strategy="hi_res",
                                 hi_res_model_name="yolox",
                                 pdf_infer_table_structure = True,
                                 chunking_strategy = "by_title",
                                 max_characters=4000,
                                 new_after_n_chars=3800,
                                 combine_under_n_chars=2000,
                                 overlap = 50)
                                 
With chunk_by_title taht does work:

chunks = chunk_by_title(elements, 
                        max_characters = 4000,
                        new_after_n_chars = 3800,
                        combine_text_under_n_chars =2000, 
                        overlap = 50,
                        )

**Environment:**
 - Using the hosted API or self hosting?
 Hosted
 - How are you calling the API? :
 from unstructured.partition.api import partition_via_api

**Comment by scanny** [comment]
Diagnosis: The new `overlap` and `overlap_all` chunking parameters are missing from `unstructured_client.models.shared.PartitionParameters`.

**Comment by scanny** [comment]
@BramVR there is a new version of `unstructured_client` (v0.21.0) that adds these parameters. If you upgrade the `unstructured_client` package locally it should work for you now.

Closing as resolved, but if you still have a problem using these parameters don't hesitate to reopen and we'll sort it out :)
