### ISSUE TITLE
How to have a healthcheck in the docker image ?

### ISSUE THREAD

**Issue by rocker1058** [Unstructured-IO/unstructured-api#380]
**Describe the bug**
i got 404 not found in my ecs log

**To Reproduce**
I have an ecs.. where I have an ec2. Within the ecs I already have my task and it is pointing to quay.io/unstructured-io/unstructured-api:4ffd8bc the image is downloaded correctly i test with docker ps... , but since I have a balancer in the ecs, to redirect to a target group that has the destinations ec2 of the docker image... the target needs a healthcheck... but since the image does not have it, I get 404 not found... what can I do to have a heathy in the docker image?

**Environment:**
I am doing a curl to localhost:8000

**Comment by yuming-long** [comment]
Hey there!
we do have health check endpoint, could you try `http://localhost:8000/healthcheck` with the quay image?

**Comment by rocker1058** [comment]
> healthcheck

thank u !!!, works

**Comment by MrZoidberg** [comment]
For those who discovered this issue - curl is not installed in this docker image, use wget to do healthchecks.

**Comment by mikenewsletters** [comment]
Thank you - been trying to figure out why the healthcheck wasn't reporting healthy - curl not installed hadn't occured to me!
