### ISSUE TITLE
Question / Upgrading API hosted on Azure

### ISSUE THREAD

**Issue by hschmied** [Unstructured-IO/unstructured-api#398]
I have a question and not a bug -- I am using the Unstructured-IO API image from the Azure Marketplace. What would be the best practice/suggested steps to upgrade a hosted instance (to get the latest version of the api running) there?

The provided documentation is detailed and quite easy to follow when it comes to spinning up a new service, but for an existing one I wasn't able to find any information.

Maybe the answer is just to redeploy another image and be done with the current one, but before I do that, I wanted to ask.

Thank you!
-HS

**Comment by awalker4** [comment]
Correct, you can upgrade by redeploying! I'll pass along that this info should be added to the docs.

**Comment by awalker4** [comment]
Going to close this - let us know if you have any other questions

**Comment by hschmied** [comment]
thank you!
