### ISSUE TITLE
bug: `partition_pdf_or_image` raises `Unsupported hardware` inside docker container

### ISSUE THREAD

**Issue by LaverdeS** [Unstructured-IO/unstructured-api#40]
In our efforts to refine the Dockerfile in [this PR](https://github.com/Unstructured-IO/pipeline-general/tree/docs/Dockerfile-update) we found that the container successfully parse some document types but for `.pdf` and `.jpg` doc types it downloads the model and then raises: `Could not initialise NNPACK! Reason: Unsupported hardware`.

**How to reproduce:**
- `make docker-build`
- `make docker-start-api`
- `curl -X 'POST' 'http://localhost:8000/general/v0.0.4/general' -F 'files=@sample-docs/layout-parser-paper.pdf'`

**Definition on done:**
- Successfully curl POST the `.pdf`, `.jpg`, `.pptx`, `.html` and `.eml` documents in the [sample-docs](https://github.com/Unstructured-IO/pipeline-general/tree/docs/Dockerfile-update/sample-docs) folder. The output should be a bunch of Unstructured elements.

**Comment by cragwolfe** [comment]
Is this issue specific to running the docker container on mac m1?

**Comment by LaverdeS** [comment]
> Is this issue specific to running the docker container on mac m1?

For now it has only appear on the M1 yeah so it can be that. If that's the reason then it should be consider when writing the documentation.

**Comment by LaverdeS** [comment]
The gist with the traceback is [here](https://gist.github.com/LaverdeS/bb05fc465cb926d0d7c965947fd62981)(inside the container).

**Comment by awalker4** [comment]
Trying to close the loop on old issues. I don't think we ended up adding anything to the docs about the hardware issue. Still worth a quick note?
