### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by sataz-ehl** [Unstructured-IO/unstructured-api#403]
Hi, apologies if I am not posting at the right place.
Would like to ask if I can locally host the API on my Windows machine?
The makefile can't be run on Windows.
Any advice or modification I need to make?

Thank you.
Jeff

**Comment by awalker4** [comment]
Hi there, sorry for the late reply. The api should work on windows, especially if you're using the docker container. Do the `make docker-build` and `make docker-start-api` commands also fail? Worst case, you can avoid dealing with the source code here, and pull the latest image directly from [our repository](https://github.com/Unstructured-IO/unstructured-api?tab=readme-ov-file#dizzy-instructions-for-using-the-docker-image).
