### ISSUE TITLE
chunking_strategy = "basic" is not accepted by API

### ISSUE THREAD

**Issue by NikitaKemarskiy** [Unstructured-IO/unstructured-api#404]
**Describe the bug**
When chunking_strategy = "basic" parameter is passed, API returns status 422. Looks like it accepts either "by_title" or no value.
<img width="1028" alt="Знімок екрана 2024-04-15 о 14 45 43" src="https://github.com/Unstructured-IO/unstructured-api/assets/28270615/a62f9f6f-135c-4e3c-8377-10b5357de7f5">

**To Reproduce**
Please provide as much info as possible:

- Filetype: PDF
- Any additional API parameters: chunking_strategy = "basic"

**Environment:**
 - Self-hosting version 0.0.65
 - Postman

**Comment by awalker4** [comment]
Hi there, sorry for the delay. We've added some features to the paid api that are not available via this repo. I'll make a ticket to clarify which params are paid only in our docs.
