### ISSUE TITLE
How to see how many pages are left in the API 1000page allowance and when it will reset

### ISSUE THREAD

**Issue by Robs-Git-Hub** [Unstructured-IO/unstructured-api#408]
Is there a way to see how many pages are left in the 1000-page allowance and the date the reset will occur?  Could be by logging into Unstructured.io website or through the API.  I've looked but not spotted it yet.  Thanks in advance for your help and I appreciate this isn't a bug report, so hope it's okay I posted the question here.

**Comment by awalker4** [comment]
Hi there, we don't currently have a way for users to log in and check this info, but we do have a dashboard on the roadmap. In the meantime, you can email support@unstructured.io with the email you used to sign up and we'll take a look for you.
