### ISSUE TITLE
Running API in a AWS ECS task is not changing the port.

### ISSUE THREAD

**Issue by Bryson14** [Unstructured-IO/unstructured-api#409]
**Describe the bug**

Feels a little bit ridiculous, but I can't change the port the service is running on. It always runs on port 8000. 

On this documentation page: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html it says you can use the command arg and Ive been passing in ["--port", "80"]. But this doesn't change anything

**To Reproduce**
Please provide as much info as possible:

Make a running container in aws ECS fargate and then try to change the port in the container definition. 

- Filetype:
- Any additional API parameters:

**Environment:**
 - Using the hosted API or self hosting?
 - How are you calling the API? (Langchain, SDKs, cUrl, etc.)

AWS self hosted

**Additional context**

**Comment by awalker4** [comment]
Hi there, apologies about that. It looks like we have the port hardcoded in the server start script. Let me make a quick pr!

**Comment by awalker4** [comment]
You should be able to add a PORT env variable in fargate now 🎉

**Comment by Bryson14** [comment]
That works. thanks!. But just to clarify that is not on the latest container image 5cbd99e2e18364aced1c62e02e923b9c29f38462b24b232a4ae7eef584e13a3c, right? This -e PORT didn't work for me on this tag

**Comment by awalker4** [comment]
Ah, seems we're having a failure in our docker publish job - I'll circle back when we're able to get the latest image out.

**Comment by awalker4** [comment]
This is now resolved in the 0.0.68 image!
