### ISSUE TITLE
bug: DOC|DOCX and PPT filetypes are UNK in web-app/docker-container

### ISSUE THREAD

**Issue by LaverdeS** [Unstructured-IO/unstructured-api#41]
In our efforts to refine the Dockerfile in [this PR](https://github.com/Unstructured-IO/pipeline-general/tree/docs/Dockerfile-update) we found that both the container and the web app for the API successfully parse some document types but for `.doc`, `.docx` and `.ppt` raise `ValueError: Invalid file. File type not support in partition`. The filetype at the point of this error is `FileType.UNK` inside `detect_filetype(filename, file)` in `unstructured.partition.auto.partition` This happens despite counting with [unstructured v0.5.0](https://github.com/Unstructured-IO/pipeline-general/blob/84d0512e1ed2b0ab744a6862af95ec4d574048f7/requirements/base.txt#L363) installed.

**How to reproduce:**
- For the image/container: `make docker-build` && `make docker-start-api`
- For the web app: `make run-web-app`
- `curl -X 'POST' 'http://localhost:8000/general/v0.0.4/general' -F 'files=@sample-docs/fake.doc'` (OR using `@sample-docs/fake.docx` or `@sample-docs/fake-power-point.ppt`.

**Definition on done:**
- Successfully curl POST the `.doc`, `docx`, `.ppt`, `.html` and `.eml` documents in the [sample-docs](https://github.com/Unstructured-IO/pipeline-general/tree/docs/Dockerfile-update/sample-docs) folder (web app and docker container). The output should be a bunch of Unstructured elements.

**Comment by cragwolfe** [comment]
What's the difference between this and https://github.com/Unstructured-IO/pipeline-general/issues/40 ?

**Comment by LaverdeS** [comment]
> What's the difference between this and https://github.com/Unstructured-IO/pipeline-general/issues/40 ?

#40 is a different error, `Could not initialise NNPACK! Reason: Unsupported hardware` happens only inside the container and is probably an issue with building detectron from source that we might solve by switching to a different base container. The web-app can parse `.pdf` and `.jpg` with no problem. Here in #41 the error seem unrelated and maybe is due to something in the tools code.

**Comment by LaverdeS** [comment]
Testing inside the container it works using filename param but not file. The gist with the traceback is [here](https://gist.github.com/LaverdeS/f2d97aeb688ba0fd8569ffabf857c1d9).

**Comment by LaverdeS** [comment]
With fix #44, `docx` is now `FileType.UNK` and part of the scope of this Issue.

**Comment by LaverdeS** [comment]
Updated parsing outputs:
Testing your branch `fix/docx-pptx-in-api`:
- `.ppt`: web-app: ☑️ **|** curl container: traceback gist [here](https://gist.github.com/LaverdeS/2e8740d6c020ca227b6e38033474191a) **|** terminal container file and filename params: traceback gist [here](https://gist.github.com/LaverdeS/e3e48ce49bdb051a781d332d98344913).
- `.doc`: web-app: ☑️ **|** curl container: ☑️ **|** terminal container file and filename params [here](https://gist.github.com/LaverdeS/f2d97aeb688ba0fd8569ffabf857c1d9).
- `.docx`: web-app: `ValueError: Invalid file /var/folders/01/tgx6z.../T/tmp9.... File type not support in partition (FileType.UNK)`. **|** curl container: `ValueError: Invalid file /tmp/tmpcug12hvc. File type not support in partition.` **|** terminal container file param: ☑️, terminal container filename param: ☑️

**Comment by awalker4** [comment]
Looks like all these filetypes are working locally and in the container now. Closing this via https://github.com/Unstructured-IO/unstructured-api/pull/82

**Comment by cragwolfe** [comment]
Does this also work if the file submitted to the API does not have a file content type specified or is "application/octet-stream"? [.ppt and .doc in particular, pretty sure .pptx and .docx are fine]

**Comment by awalker4** [comment]
Yep, verified that it works locally and in the container by printing out the inferred content type (`application/vnd.ms-powerpoint` and `application/msword`.
