### ISSUE TITLE
bug: TXT-parse fails for web-app/docker-container

### ISSUE THREAD

**Issue by LaverdeS** [Unstructured-IO/unstructured-api#43]
In our efforts to refine the Dockerfile in [this PR](https://github.com/Unstructured-IO/pipeline-general/tree/docs/Dockerfile-update) we found that both the web app successfully parse some document types but for `.txt` it raises: `TypeError: cannot use a string pattern on a bytes-like object` in both the container and web app.

**How to reproduce:**
- For the image/container: `make docker-build` && `make docker-start-api`
- For the web app: `make run-web-app`
- `curl -X 'POST' 'http://localhost:8000/general/v0.0.4/general' -F 'files=@sample-docs/fake-text.txt'`

**Definition on done:**
- Successfully curl POST the `.txt`, `.html` and `.eml` documents in the [sample-docs](https://github.com/Unstructured-IO/pipeline-general/tree/docs/Dockerfile-update/sample-docs) folder (web app and docker container. The output should be a bunch of Unstructured elements.

**Comment by LaverdeS** [comment]
Testing inside the container it works using filename param but not file. The gist with the traceback is [here](https://gist.github.com/LaverdeS/66dbec3f390144d66af7956f8c7e3c5f).

**Comment by awalker4** [comment]
Going to close this ancient bug.
