### ISSUE TITLE
Local api latest version via docker is worst than the api version

### ISSUE THREAD

**Issue by zakariaabboud** [Unstructured-IO/unstructured-api#437]
I was trying to use unstructured to extract a table from pdf but when I used the open source api and the api from the site I found out that the local version is really worst than the other version in table extraction, is this normal ?

**Comment by zakariaabboud** [comment]
I used the same strategy and model for both : hi_res, yolox

**Comment by awalker4** [comment]
Hi there! Our paid API includes better performance and our latest models, so this is expected.

**Comment by alexanderniebuhr** [comment]
@awalker4 Understandable. Is there any comparison table or can you provide one, which choose which differences in models or performance there is between self-hosted and the SaaS version?

**Comment by alexanderniebuhr** [comment]
Thanks for linking the docs. But it doesn't show numbers or actual model names :/
