### ISSUE TITLE
[Query] Can unstructured-api be used for document loading as well from various sources?

### ISSUE THREAD

**Issue by S1LV3RJ1NX** [Unstructured-IO/unstructured-api#440]

**Comment by awalker4** [comment]
Hi there! The unstructured-api repo is only a wrapper for the library's partitioning functionality. If you'd like to do the partitioning remotely, you can use the ingest CLI with all its connectors, but add the `partition-by-api` argument. Then you can set the url to point to your `unstructured-api` server. Here's an example using the `local` ingest arguments, but `by-api` should be supported with any connector.

```
unstructured-ingest \
  local \
    --input-path local-ingest-source \
    --partition-by-api \
    --partition-endpoint $UNSTRUCTURED_API_URL \
    --strategy fast \
  local \
    --output-dir local-ingest-output
```
