### ISSUE TITLE
SDKError: API error occurred: Status 401 {"detail":"API key is invalid, please provide a valid API key in the header."}

### ISSUE THREAD

**Issue by justinsyu** [Unstructured-IO/unstructured-api#441]
Hello, this issue just began yesterday (after almost two weeks with no problems since I created a trial account). I tried creating a new API key and am still getting the same error. Below is my code for reference. Please help! Thank you!

import os
from getpass import getpass

os.environ["UNSTRUCTURED_API_KEY"] = getpass("Enter your Unstructured API Key:")
os.environ["UNSTRUCTURED_API_URL"] = getpass("Enter your Unstructured API URL:")
os.environ["ASTRA_DB_API_ENDPOINT"] = input("Enter your Astra DB API Endpoint: ")
os.environ["ASTRA_DB_APPLICATION_TOKEN"] = getpass("Enter your Astra DB Token: ")
os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API Key: ")

from langchain_community.document_loaders import UnstructuredAPIFileLoader

loader = UnstructuredAPIFileLoader(
api_key=os.environ["UNSTRUCTURED_API_KEY"],
file_path="filename.pdf",

)
simple_docs = loader.load()
len(simple_docs)

**Comment by srini047** [comment]
> Hello, this issue just began yesterday (after almost two weeks with no problems since I created a trial account). I tried creating a new API key and am still getting the same error. Below is my code for reference. Please help! Thank you!
> 
> import os from getpass import getpass
> 
> os.environ["UNSTRUCTURED_API_KEY"] = getpass("Enter your Unstructured API Key:") os.environ["UNSTRUCTURED_API_URL"] = getpass("Enter your Unstructured API URL:") os.environ["ASTRA_DB_API_ENDPOINT"] = input("Enter your Astra DB API Endpoint: ") os.environ["ASTRA_DB_APPLICATION_TOKEN"] = getpass("Enter your Astra DB Token: ") os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API Key: ")
> 
> from langchain_community.document_loaders import UnstructuredAPIFileLoader
> 
> loader = UnstructuredAPIFileLoader( api_key=os.environ["UNSTRUCTURED_API_KEY"], file_path="filename.pdf",
> 
> ) simple_docs = loader.load() len(simple_docs)

Same issue if being faced by me as well. But I'm using the [unstructured haystack integration](https://github.com/deepset-ai/haystack-core-integrations/tree/main/integrations/unstructured#unstructured-fileconverter-haystack).

**Comment by Coniferish** [comment]
Hi @justinsyu and @srini047,
The 401 error is likely because you are connecting to the free api address (`https://api.unstructured.io/`) and not `https://api.unstructuredapp.io`. We are in the midst of transitioning to a single endpoint at our new [serverless API](https://docs.unstructured.io/api-reference/api-services/saas-api-development-guide). You can see both the Serverless and Free APIs listed at the top of this [landing page ](https://docs.unstructured.io/api-reference/api-services/overview), but the Free API address is being phased out. There is still a free 14-day trial for the Unstructured Serverless API, though.

Closing this for now, but please reach out if you still have trouble with api key.

**Comment by btcmonte** [comment]
still seeing the issue - I'm currently using llamaParse, and testing to see what the differences between Unstructured and LlamaParse are?  can the free version allow for 1 document and 15 pages?

(unstructured2) bob@bob:~$ /home/bob/anaconda3/envs/unstructured2/bin/python /home/bob/Documents/python/unstructured/import-test.py
INFO: Preparing to split document for partition.
INFO: Starting page number set to 1
INFO: Concurrency level set to 15
INFO: Determined optimal split size of 2 pages.
INFO: Document split into 2, 2-paged sets.
INFO: Partitioning 2, 2-paged sets.
INFO: Partitioning set #1 (pages 1-3).
INFO: Partitioning set #2 (pages 3-4).
/home/bob/anaconda3/envs/unstructured2/lib/python3.11/site-packages/unstructured_client/_hooks/custom/suggest_defining_url.py:15: UserWarning: If intending to use the paid API, please define `server_url` in your request.
  warnings.warn(
INFO: HTTP Request: POST https://api.unstructured.io/general/v0/general "HTTP/1.1 401 Unauthorized"
WARNING: Failed to partition set #1, its elements will be omitted in the final result.
WARNING: Failed to partition set #2, its elements will be omitted in the final result.
ERROR: Failed to partition the document.
API error occurred: Status 401
{"detail":"API key is malformed, please type the API key correctly in the header."}
