### ISSUE TITLE
Images are not detected for docx/pptx

### ISSUE THREAD

**Issue by s-arme** [Unstructured-IO/unstructured-api#447]
Hi,
This my client call 
```
const { elements } = await client.general.partition({
      partitionParameters: {
        files: {
          fileName: filename,
          content: data,
        },
        strategy: Strategy.HiRes,
        skipInferTableTypes: ['jpg+png'],
        extractImageBlockTypes: ['Image'],
      },
    });
   ```
   When I input any docx, doc or pptx no Image element is included in the output. I'm using ` quay.io/unstructured-io/unstructured-api:0.0.76` and the reference [Travel photo timeline.pptx](https://github.com/user-attachments/files/16570437/Travel.photo.timeline.pptx) result in no image being deteted.
   
Also as I read  [#1615](https://github.com/Unstructured-IO/unstructured/issues/1615) and [#2968](https://github.com/Unstructured-IO/unstructured/issues/2968) image extraction should have already been implemented but I can not extract any image with latest `0.0.76` tag.

**Comment by awalker4** [comment]
Hi there, unfortunately image extraction from Office files is a paid feature, not included in our open source API. Please see [this section](https://docs.unstructured.io/open-source/introduction/overview#limits) in the docs for our open source limitations. We do have a 14 day free trial on our [serverless API](https://docs.unstructured.io/api-reference/api-services/saas-api-development-guide) if you'd like to give it a spin. The same SDK call should work once you have an API key.
