### ISSUE TITLE
How could I use the unstructured-api docker container without internet?

### ISSUE THREAD

**Issue by quzhixue-Kimi** [Unstructured-IO/unstructured-api#482]
Hi there,

The latest docker image of unstructured-api has been downloaded with internet.
![image](https://github.com/user-attachments/assets/5f428aca-a12e-4981-82c1-17a66db5e8b1)

And I ran 'docker save -o api.tar downloads.unstructured.io/unstructured-io/unstructured-api:latest' command to export the docker image, uploading the docker image to a test ubuntu server, this test ubuntu server has no internet!

I ran the 'docker run -itd --name api -p 8000:8000 downloads.unstructured.io/unstructured-io/unstructured-api:latest' command to start a container.

Tried to extract a pdf file with curl command like: 'curl -X 'POST' 'http://localhost:8000/general/v0/general' -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F 'files=@mypdf.pdf' -F 'strategy=hi_res''

Since, there is no internet on test ubuntu server, there is one error occurred with 'huggingface.co' domain could not be resolved.

I tried to re-run the container as 'docker run -itd --name api -p 8000:8000 -e HF_DATASETS_OFFLINE=1 downloads.unstructured.io/unstructured-io/unstructured-api:latest', but it failed also.

It is appreciated that you could guide me how to run the container which could be used to extracted the PDF file without internet.

Any feedback is greatful.

BR
Kimi

**Comment by quzhixue-Kimi** [comment]
The reason why I want to use the unstructured-api docker container is that I need a restful api to extract PDF file in flowise web ui.

I found there is the plugin of unstructured-api

![image](https://github.com/user-attachments/assets/e593f6a0-5736-4b38-b397-c17b272d4de5)

**Comment by tangkunyin** [comment]
> The reason why I want to use the unstructured-api docker container is that I need a restful api to extract PDF file in flowise web ui.
> 
> I found there is the plugin of unstructured-api
> 
> ![image](https://private-user-images.githubusercontent.com/8235746/396381586-e593f6a0-5736-4b38-b397-c17b272d4de5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0ODkwNDQsIm5iZiI6MTczNDQ4ODc0NCwicGF0aCI6Ii84MjM1NzQ2LzM5NjM4MTU4Ni1lNTkzZjZhMC01NzM2LTRiMzgtYjM5Ny1jMTdiMjcyZDRkZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMThUMDIyNTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDhmY2E0MWQ0OTQ3Mjg1YTg5ODU0MjAyM2VmZTE4ODU5NWQ4NTAzYTIxNmViMDBmYjQwN2VjMzA4Y2I2NDkyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.88QPnv-_u1Kh-HYtEjmxBixtqALBgowgAJK4N7oSWOM)

Hello there, Can you tell more about where can we get the plugin and how to use it? Thanks...

**Comment by quzhixue-Kimi** [comment]
Hi there,

You may download and deploy the flowise locally via docker, https://github.com/FlowiseAI/Flowise

Open flowise, click the document stores and add a new one, finally add a new document loader. Select the unstructured file loader


![image](https://github.com/user-attachments/assets/58879f08-a2e8-4762-a587-7543e0954c22)

BR
Kimi

**Comment by quzhixue-Kimi** [comment]
Since there is no response, close this issue and try to find the other solution

**Comment by tangkunyin** [comment]
@quzhixue-Kimi I suddenly remember that, with `strategy=hi_res`, there will be a downloading occurred if there is no the model file in your container environment.

To fix with no internet and works well, maybe you can download models previously. But the question I suffered is that I don't know how to  [How to use a local custom model for hi_res strategy](https://github.com/Unstructured-IO/unstructured-api/issues/484) 

I have posted a issue, hopefully the problem can be solved.... 🤣 😏

**Comment by RWayne93** [comment]
@tangkunyin @quzhixue-Kimi to successfully run the api service locally without Internet you will need to download the models from huggingface. 

When you have internet the models are downloaded in the container inside .cache/huggingface/hub 

You can exec into the container and ls that path to see what models you would need to download from huggingface.
