### ISSUE TITLE
Fast Parameter

### ISSUE THREAD

**Issue by theZaX** [Unstructured-IO/unstructured-api#54]
Being able to use the fast mode of Unstructured via the api is very important for our use case.

Our users interact in "interactive-mode" and wait on the same page while the document processes. None of them have uploaded a document that really needed OCR and are they are ok with using other services for that before uploading to our service.

**Comment by cragwolfe** [comment]
The makes a lot of sense, we will add support for a `fast` parameter to the API in the near future. Thanks @theZaX!

**Comment by cragwolfe** [comment]
Running with the`fast` strategy is now the default! The `hi_res` strategy may also be requested, however, e.g.:

```
 curl -X 'POST' \
  'https://api.unstructured.io/general/v0/general' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'files=@sample-docs/layout-parser-paper.pdf' \
  -F 'strategy=hi_res' \
  | jq -C . | less -R 
  ```
