### ISSUE TITLE
Pass the file as a URL and not as a blob

### ISSUE THREAD

**Issue by theZaX** [Unstructured-IO/unstructured-api#55]
It would be nice and more efficient to have the option of passing the file as a downloadable url rather than a blob so I don't have to download the file in my application server and then send it to unstructured (this is more efficient and avoids the 32mb body limit on some hosting platforms.

**Comment by cragwolfe** [comment]
@theZaX , I see the motivation. But, I have doubts from a free-internet hosted API provider perspective that allowing downloads from arbitrary locations on the internet is something that should be supported, or at least be the default.

**Comment by theZaX** [comment]
Yeah although it seems that accepting arbitrary files from an open api could be just as bad. I'm not sure the extra download step is what would be causing the security vulnerability. 

The image captioning api by Microsoft is an example of an api that accepts these sorts of parameters. They accept a file blob or a source url. 

https://westcentralus.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-2/operations/56f91f2e778daf14a499f21b

**Comment by cragwolfe** [comment]
Strictly speaking, it's at least as bad as accepting any arbitrary files, because of any potential network-related vulnerabilities or additional networking costs on top of whatever payload you finally end up with.

The Microsoft example has a key to identify the user, it seems: `-H "Ocp-Apim-Subscription-Key: {subscription key}"`, so not 100% analogous.

That said, I see no reason not to add a sample notebook to the repo that allows this.

**Comment by theZaX** [comment]
Awesome, I plan on self hosting anyway so I'll implement the code in the sample notebook in my fork.

Thanks for all the help!

**Comment by cragwolfe** [comment]
A bit more detail on the opinionated way to add a custom API for "pipeline-" repo such as this.

The idea is to basically add an additional [pipeline-](https://github.com/Unstructured-IO/unstructured-api/tree/main/pipeline-notebooks) notebook and then rely on code generation to create the new API (leaving the existing/upstream `/general/v0.0.4/general` in tact). The steps are:

* create a new `pipeline-<name>.ipynb` notebook in pipeline-notebooks/ . A copy of that pipeline_api in that notebook gets invoked when the new endpoint `/general/v0.0.4/<name>` is invoked (after the last step in this list).
* add an `m_url` kwarg to the `pipeline_api` signature. This becomes an optional multi-string form variable `url` (yes, without the m_-prefix) in the generated API. It must have a default, which could be empty list. You can add an arbitrary number of `m_` params that follow the same convention.
* of course, update the pipeline_api function to do the right thing with the m_url kwarg
* From a the root of the repo, call `make generate-api` to create the `<name>.py` module in https://github.com/Unstructured-IO/unstructured-api/tree/main/prepline_general/api

That's it! You could also delete `https://github.com/Unstructured-IO/unstructured-api/blob/main/prepline_general/api/general.py` which would leave your new api as the only one accessible, and viewable under https://<your-service-name>/docs.

Note that there are additional make targets to make sure that notebooks checked in are clean and have reproducible outputs:

`make tidy-notebooks` and `make check-notebooks`

and one to make sure that generated API's match the pipeline-notebook:

`make api-check`

that you could tweak (if needed) for your environment.

Finally a note on the version, it's automatically inferred from [here](https://github.com/Unstructured-IO/unstructured-api/blob/main/preprocessing-pipeline-family.yaml#L2) during `make generate-api`

**Comment by awalker4** [comment]
Hi @theZaX - going to close this old issue as it sounds like you implemented what you needed.
